spring.application.name=BlinkitPicker
spring.datasource.url=jdbc:postgresql://localhost:5432/blinkit_db
spring.datasource.username=springboot_app
spring.datasource.password=27A*Njq067e%FJN&r@%AbWFw93#Qa0YrUwcAaDgY
spring.jpa.hibernate.ddl-auto=update

api.base=https://storeops-api.blinkit.com/v1/slots
list.slots.url=/list_slots_by_site
book.slot.url=/book
cancel.slot.url=/cancel
available.dates.url=/available_dates

auth.base=https://storeops-api.blinkit.com
send.otp.url=/auth/api/v1/phone/send_otp

verify.otp.url=/auth/api/v1/phone/verify_otp
login.url=https://storeops-api.blinkit.com/ops-management-api/storeops/login/


cognito.clientId=1rog6peta8n3n69tp886dmfeie
cognito.poolId=ap-southeast-1_MFpIMqwOW

jwt.secret=!8!UejqyAxDT*Y!R9rE9WHU9RKts$^mAd4MWnTMFe%x*dkHJ7EfSaVw$SwkyJh74
jwt.expiration=86400000
jwt.refresh-expiration=604800000
