spring.application.name=BlinkitPicker
spring.datasource.url=jdbc:postgresql://localhost:5432/blinkit_db
spring.datasource.username=springboot_app
spring.datasource.password=27A*Njq067e%FJN&r@%AbWFw93#Qa0YrUwcAaDgY
spring.jpa.hibernate.ddl-auto=update
